import { createContext, useContext, useMemo, useState } from 'react';

// Loads every locale/*.json file automatically (English plus all 22
// Eighth-Schedule languages generated by scripts/generateTranslations.js)
// so adding a new locale file is enough on its own - nothing here needs to
// change. { eager: true } bundles them all at build time rather than
// fetching on demand, which is fine at this dictionary's size.
const localeModules = import.meta.glob('../locales/*.json', { eager: true });
const DICTIONARIES = {};
for (const path in localeModules) {
  const code = path.match(/([a-z]+)\.json$/)[1];
  DICTIONARIES[code] = localeModules[path].default ?? localeModules[path];
}

// Native display names for the Eighth Schedule languages Bhashini
// translates the site into (see backend/utils/bhashiniClient.js) - this is
// the WEBSITE's language list, deliberately separate from the IVR
// simulator, which keeps its own smaller, hand-verified set (en/ta/hi/te).
const NATIVE_NAMES = {
  en: 'English', as: 'অসমীয়া', bn: 'বাংলা', brx: 'बड़ो', doi: 'डोगरी',
  gu: 'ગુજરાતી', hi: 'हिन्दी', kn: 'ಕನ್ನಡ', ks: 'کٲشُر', kok: 'कोंकणी',
  mai: 'मैथिली', ml: 'മലയാളം', mni: 'মৈতৈলোন্', mr: 'मराठी', ne: 'नेपाली',
  or: 'ଓଡ଼ିଆ', pa: 'ਪੰਜਾਬੀ', sa: 'संस्कृतम्', sat: 'ᱥᱟᱱᱛᱟᱲᱤ', sd: 'سنڌي',
  ta: 'தமிழ்', te: 'తెలుగు', ur: 'اردو',
};

// Only list a language if its locale file actually exists (generated) -
// keeps the switcher honest rather than offering a language with nothing
// behind it.
export const SUPPORTED_LANGS = Object.keys(DICTIONARIES)
  .filter((code) => NATIVE_NAMES[code])
  .sort((a, b) => (a === 'en' ? -1 : b === 'en' ? 1 : NATIVE_NAMES[a].localeCompare(NATIVE_NAMES[b])))
  .map((code) => ({ code, label: NATIVE_NAMES[code] }));

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('siteLang') || 'en');

  const setLang = (code) => {
    setLangState(code);
    localStorage.setItem('siteLang', code);
  };

  const t = useMemo(() => {
    const dict = DICTIONARIES[lang] || DICTIONARIES.en;
    return (key) => dict[key] ?? DICTIONARIES.en[key] ?? key;
  }, [lang]);

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
